### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.repository'

### ISSUE THREAD

**Issue by xiongxiong1996** [Hawkeye-FineGrained/Hawkeye#1]
I followed the steps inscribed to install it, but there was a problem ：ModuleNotFoundError: No module named 'utils.repository'.
Is there a problem with my path settings?

(hawkeye) root:/tmp/pycharm_project_Hawkeye/Hawkeye# python Examples/APINet.py --config configs/APINet.yaml
Traceback (most recent call last):
  File "Examples/APINet.py", line 8, in <module>
    from model.loss.APINet_loss import APINetLoss
  File "/tmp/pycharm_project_Hawkeye/Hawkeye/model/__init__.py", line 1, in <module>
    from .methods import *
  File "/tmp/pycharm_project_Hawkeye/Hawkeye/model/methods/__init__.py", line 1, in <module>
    from .BCNN import BCNN
  File "/tmp/pycharm_project_Hawkeye/Hawkeye/model/methods/BCNN.py", line 3, in <module>
    from model.backbone import vgg16
  File "/tmp/pycharm_project_Hawkeye/Hawkeye/model/backbone/__init__.py", line 1, in <module>
    from .vgg import vgg11, vgg13, vgg16, vgg19, vgg11_bn, vgg13_bn, vgg16_bn, vgg19_bn
  File "/tmp/pycharm_project_Hawkeye/Hawkeye/model/backbone/vgg.py", line 7, in <module>
    from model.registry import BACKBONE
  File "/tmp/pycharm_project_Hawkeye/Hawkeye/model/registry.py", line 1, in <module>
    from utils.repository import Repository
ModuleNotFoundError: No module named 'utils.repository'

**Comment by xiongxiong1996** [comment]
I found that there was a problem with sys.path, 
I ran it fine with pycharm, but the command didn't.
