### ISSUE TITLE
t() expects a tensor with <= 2 dimensions, but self is 4D

### ISSUE THREAD

**Issue by haidongwang3629** [Hawkeye-FineGrained/Hawkeye#3]
Thanks for the awosome sharing! Really appearate this work!

While run the testing scripts: python3 test.py --config configs/test.yaml  (i have already trained APINet )

`experiment:
  name: test_APINet
  cuda: [0]
dataset:
  name: cub
  root_dir: data/bird/CUB_200_2011/images
  meta_dir: metadata/cub
  batch_size: 32
  num_workers: 4
  transformer:
    resize_size: 448
    image_size: 448
model:
  name: APINet
  num_classes: 200
  load: results/APINet/API_res101_1/best_model.pth`

it reports the following message: 

`Traceback (most recent call last):
  File "/home/haidongwang/code/Hawkeye/test.py", line 147, in <module>
    tester.test()
  File "/home/haidongwang/code/Hawkeye/test.py", line 119, in test
    self.validate()
  File "/home/haidongwang/code/Hawkeye/test.py", line 129, in validate
    self.batch_validate(data)
  File "/home/haidongwang/code/Hawkeye/test.py", line 135, in batch_validate
    logits = self.model(images)
  File "/home/haidongwang/anaconda3/envs/chenli/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/haidongwang/code/Hawkeye/model/methods/APINet.py", line 34, in forward
    intra_pairs, inter_pairs, intra_labels, inter_labels = self.get_pairs(pool_out, targets)
  File "/home/haidongwang/code/Hawkeye/model/methods/APINet.py", line 77, in get_pairs
    distance_matrix = pdist(embeddings).detach().cpu().numpy()
  File "/home/haidongwang/code/Hawkeye/model/methods/APINet.py", line 117, in pdist
    distance_matrix = -2 * vectors.mm(torch.t(vectors)) + vectors.pow(2).sum(dim=1).view(1, -1) \
**RuntimeError: t() expects a tensor with <= 2 dimensions, but self is 4D`**

**Comment by yulingchen123** [comment]
我也遇见了这个问题，请问你解决了么

**Comment by yulingchen123** [comment]
我解决了，不能使用test.yaml，因为APINet的训练和验证不一样，验证阶段不使用get_pairs, 也就是，
elif flag == 'val':
            return self.fc(pool_out)
但是直接在test.py里面改也不行，打印出来pool_out是这样的
pool out shape: torch.size([16,2048,2,2])，直接在config.py里面放
![1](https://github.com/Hawkeye-FineGrained/Hawkeye/assets/140585057/0b4d3fd6-3afb-47b6-9ba5-cea9fe624be2)
然后
![2](https://github.com/Hawkeye-FineGrained/Hawkeye/assets/140585057/890b0e8a-5d8e-4af3-b265-07a8f4d66ecc)
然后运行test.py，就有测试结果了
<img width="675" alt="7fa286cb0193401f2e6e33df9345514" src="https://github.com/Hawkeye-FineGrained/Hawkeye/assets/140585057/bde907e2-35df-449a-981f-cf71bc36f6dd">
至于为什么加载APINet.yaml会这样但是test.yaml就不行，我也不太清楚，我还特分了val.txt和test.txt,输出的结果就是test.txt测试集

**Comment by yulingchen123** [comment]
总结就是不要加载test.yaml，加载APINet.yaml试试，在APINet.yaml里面把最佳权重路径写上

**Comment by yulingchen123** [comment]
至于t() 期望张量具有 <= 2 维，但自身是 4D，是因为验证阶段不应该运行get_pairs函数，对应文章里面说的，只在训练阶段成对输入图片，验证阶段正常输入，但是test文件里面好像并没有规定val的时候不使用get_pairs（）,所以我在test里面加了个val标签flag，但是随后显示pool out 张量不匹配，我始终无法解决，最后选择不加载test.yaml，加载APINet.yaml，最后运行test.py，显示结果成功
![image](https://github.com/Hawkeye-FineGrained/Hawkeye/assets/140585057/a95e03aa-00e6-4868-b4a3-4f520481636b)


> 我解决了，不能使用test.yaml，因为APINet的训练和验证不一样，验证阶段果get_pairs，也就是， elif flag == 'val': return self.fc(pool_out) 但是直接在test.py里面改也不行，打印出来pool_out是这样的 pool out shape: torch.size([16,2048,2,2])，直接在config.py里面放 然后 然后运行test.py，就有测试结果了 至于为什么加载APINet.yaml会这样但是test.yaml就不行，我也不太清楚，我还特分了val.txt和test.txt,输出的结果就是test.txt测试集 ![1](https://private-user-images.githubusercontent.com/140585057/334427662-0b4d3fd6-3afb-47b6-9ba5-cea9fe624be2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5MDI4NDUsIm5iZiI6MTcxNjkwMjU0NSwicGF0aCI6Ii8xNDA1ODUwNTcvMzM0NDI3NjYyLTBiNGQzZmQ2LTNhZmItNDdiNi05YmE1LWNlYTlmZTYyNGJlMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOFQxMzIyMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMjdmMThmYjMyNzVhMzQ3NmQyY2I4MjYzZWU3MjFiNWIxNjJmZDRkZTMxOThhYmRmZjc5ZDExOTFhYjFjZDM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LWVioARVGXe7QQtIx5-UkBBwK585fhxSBBpS3sUVQUQ) ![2](https://private-user-images.githubusercontent.com/140585057/334427747-890b0e8a-5d8e-4af3-b265-07a8f4d66ecc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5MDI4NDUsIm5iZiI6MTcxNjkwMjU0NSwicGF0aCI6Ii8xNDA1ODUwNTcvMzM0NDI3NzQ3LTg5MGIwZThhLTVkOGUtNGFmMy1iMjY1LTA3YThmNGQ2NmVjYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOFQxMzIyMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDQ2ZTk4YWMyY2UwOGEyYzNkYzFlY2Y5YzM2OTM4YjBmY2QyODNlMTI1OGEzNjFlOGY3ZDAzNWY1ODg5N2IyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9cYaLaxYD_IZRMdJCuc187ie99NogdXxzX5U_sKJLv4) <img alt="7fa286cb0193401f2e6e33df9345514" width="675" src="https://private-user-images.githubusercontent.com/140585057/334428016-bde907e2-35df-449a-981f-cf71bc36f6dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5MDI4NDUsIm5iZiI6MTcxNjkwMjU0NSwicGF0aCI6Ii8xNDA1ODUwNTcvMzM0NDI4MDE2LWJkZTkwN2UyLTM1ZGYtNDQ5YS05ODFmLWNmNzFiYzM2ZjZkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOFQxMzIyMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTllNmRmM2VhNGI0NTc1ZWQyZjg2NjMxNTY0NTk2ZDk0NjczMGFmZTZkNjY2ZjA5MTRmNmNmNTdmNmIwM2MyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BFXAY34d8nBokoz60E6xStRs1ytGYVsq5_6EGs_XdUQ">

**Comment by fanqiegu0** [comment]
> 我也遇见了这个问题，请问你解决了么

你好同学，我有一些细粒度图像分类的问题想要咨询您，不知道您方便吗？（主要是关于能否用自己建立的数据集进行相关的细粒度图像分类）
